/// <reference types="cypress"/>

describe('US-12-Funcionalidade: Cadastro de membros', () => {
  it('Cadastro de campos obrigatórios', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-firstname').type('Otavio')
    cy.get('#signup-lastname').type('Feitosa')
    cy.get('#signup-email').type('teste345@teste.com')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-password').type('Teste@2121')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'Cadastro realizado com sucesso!')
  })
  it('Validação de email já cadastrado', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-firstname').type('Otavio')
    cy.get('#signup-lastname').type('Feitosa')
    cy.get('#signup-email').type('teste4@teste.com')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-password').type('Teste@2121')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'Este email já está cadastrado.')
  })
  it('Validação de mensagem de erro com nome vazio', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-lastname').type('Feitosa')
    cy.get('#signup-email').type('teste4@teste.com')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-password').type('Teste@2121')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'Nome não pode estar vazio')
  })
  it('Validação de mensagem de erro com sobrenome vazio', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-firstname').type('Otavio')
    cy.get('#signup-email').type('teste5@teste.com')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-password').type('Teste@2121')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'Sobrenome não pode estar vazio')
  })
  it('Validação de mensagem de erro com email inválido', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-firstname').type('Otavio')
    cy.get('#signup-lastname').type('Feitosa')
    cy.get('#signup-email').type('testeteste.com')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-password').type('Teste@2121')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'E-mail deve ser um email válido')
  })
  it('Validação de mensagem de erro com email vazio', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-firstname').type('Otavio')
    cy.get('#signup-lastname').type('Feitosa')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-password').type('Teste@2121')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'E-mail não pode estar vazio')
  })
  it('Validação de mensagem de erro com senha fraca', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-firstname').type('Otavio')
    cy.get('#signup-lastname').type('Feitosa')
    cy.get('#signup-email').type('teste6@teste.com')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-password').type('Teste')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'Senha deve ter pelo menos 8 caracteres, incluir uma letra maiúscula, um número e um caractere especial (!@#$&*)')
  })
  it('Validação de mensagem de erro com senha vazia', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#signup-firstname').type('Otavio')
    cy.get('#signup-lastname').type('Feitosa')
    cy.get('#signup-email').type('teste4@teste.com')
    cy.get('#signup-phone').type('1845451136')
    cy.get('#signup-button').click()
    cy.get('#signup-response').should ('contain' , 'Senha não pode estar vazia')
  }) 

}) 

describe('US-09-Funcionalidade: Busca de filmes', () => { 
  it('Validação de busca de filmes', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#search-input').type('Harry Potter')
    cy.get('#search-button').click()
  })
  it('Validação do botão de limpar busca', () => {
    cy.visit('http://192.168.0.162:8081/')
    cy.get('#search-input').type('Harry Potter')
    cy.get('#clear-button').click()
  })
})